### ISSUE TITLE
Does not work with Exaile 0.3.2.1

### ISSUE THREAD

**Issue by millioner** [vrtx64/vk_exaile#5]
The plugin does not work with Exaile 0.3.2.1
It writes "Plugin archive contains an unsafe path."
Can you please try to fix it?

**Comment by ankx** [comment]
Can't install. But work if I copy sources in plugin dir. (~/.local/share/exaile/plugins/vk_exaile).

**Comment by millioner** [comment]
Yes, I know about that. Two commands:
cd ~/.local/share/exaile/plugins/
git clone git://github.com/vrtx64/vk_exaile.git

But anyway it is strange issue

**Comment by ankx** [comment]
Can you unzip plugin files? I can't. All archivers show error. Packing bug?

**Comment by millioner** [comment]
No, I cannot unzip those files. Tried to do it... 
According to documentation (http://exaile.org/wiki/index.php?title=PluginDevelopment#Create_a_Plugin_Archive) it really looks like a packing issue.

**Comment by vrtx64** [comment]
Hello!
What file do you use?
Please, try rename this file to vk_exaile.exz and install it.

**Comment by whoizit** [comment]
0.3.2.2 тоже самое. Переименование помогло

**Comment by amadi** [comment]
Дополню. Получилось установить плагин на ubuntu 12.04 с установленным Exile из репозиториев. Всего навсего перенесите файл плагина из папки "Загрузки" куда-нибудь в другое место... Скорее всего "Plugin archive contains an unsafe path." ругается на небезопасность папки загрузок=)
Р.S. Виндой так попахивает=)

**Comment by vikbrdin** [comment]
При установке пишет 'Main' object has no attribute 'add_panel'
